integration:
  github:
    api:
      url: 'http://localhost:7070'
      version:
        key: 'X-GitHub-Api-Version'
        value: 2022-11-28
spring:
  jackson:
    visibility:
      field: any
server:
  error:
    include-message: ALWAYS